version: '3.8'

services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./project:/app
      - /app/node_modules
      - /app/.next
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/optiwork
      - REACT_APP_API_URL=http://localhost:5000  # Add this to connect to Flask API
    depends_on:
      - db
      - flask  # Add dependency on Flask service
    restart: unless-stopped
    networks:
      - app-network

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
    env_file:
      - ./flask/.env
    environment:
      - CORS_ORIGIN=http://localhost:3000  # Add CORS configuration
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=optiwork
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: