version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./project/Dockerfile
    ports:
      - "3000:3001"
    volumes:
      - ./project:/app
    environment:
      - DATABASE_URL=mysql://user:userpassword@db/optiwork
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: optiwork
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
